GET http://localhost:3000/api/notas

###
GET http://localhost:3000/api/notas/68dc4fe20649184643979f0d

###

POST http://localhost:3000/api/notas
Content-Type: application/json

{
  "title": "Segunda nota creada para mi db",
  "content": "Contenido de la segunda nota creada para mi db"
}

###

DELETE http://localhost:3000/api/notas/68dc4fe20649184643979f0d

###
PUT http://localhost:3000/api/notas/68dc4cdee36b22732c0b5ce2
Content-Type: application/json

{
  "title": "Nota actualizada nueva",
  "content": "Contenido actualizado de la nota"
}